version: '3'

services:
  kuruman:
    container_name: kuruman
    build: .
    command: gunicorn kuruman.asgi -w 1 --threads 2 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --preload --timeout 60 --graceful-timeout 60
    volumes:
      - .:/code
    expose:
      - 8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.kuruman.rule=Host(`kuruman.longbowou.com`,`www.kuruman.longbowou.com`)
      - traefik.http.routers.kuruman.tls=true
      - traefik.http.routers.kuruman.tls.certresolver=le
      - traefik.port=8000
      - traefik.docker.network=traefik-proxy
    networks:
      - traefik-proxy
    restart: unless-stopped

networks:
  traefik-proxy:
    external: true